version: "3.8"

services:
    
    cms:
        container_name: cms
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            GOBLOG_ENV: docker
        ports:
            - 8080:8080
        depends_on:
            - db
        networks:
            - goblog

networks:
    goblog:
        driver: bridge