version: "3.8"

services:
    db:
        image: postgres:16-alpine
        container_name: db
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-docker}
            PGDATA: /data/postgres
        volumes:
            - postgres_data:/data/postgres
        ports:
            - 5432:5432
        networks:
            - goblog

    pgadmin:
        image: dpage/pgadmin4:8.0
        container_name: pgadmin
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-nomail@nomail.com}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-docker}
            PGADMIN_CONFIG_SERVER_MODE: "False"
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        ports:
            - ${PGADMIN_PORT:-5050}:80
        networks:
            - goblog
  
networks:
    goblog:
        driver: bridge

volumes:
    postgres_data:
    pgadmin_data:
